---
- name: Create Kibana certificate directory
  ansible.builtin.file:
    path: /etc/kibana/certs
    state: directory
    owner: root
    group: kibana
    mode: "0750"

- name: Trust the Elasticsearch CA in Kibana
  ansible.builtin.copy:
    src: "{{ elk_elasticsearch_ca }}"
    dest: /etc/kibana/certs/http_ca.crt
    remote_src: true
    owner: root
    group: kibana
    mode: "0640"
  notify: Restart Kibana

- name: Configure Kibana
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: "0660"
  notify: Restart Kibana

- name: Start Kibana
  ansible.builtin.service:
    name: kibana
    state: started
    enabled: true
