---
- name: Configure logging server
  hosts: elk
  become: true
  roles:
    - role: elk
      tags: elk
    - role: kibana_dashboard
      tags: kibana_dashboard

- name: Configure web server
  hosts: web
  become: true
  roles:
    - role: apache
      tags: apache
    - role: filebeat
      tags: filebeat
